sudo: requesting
services:
    - docker

script:
    - docker build -t subhadesigns/node .
    - docker images subhadesigns/node

before deploy:
    - docker login -u subhamrgn -p Newmac@143

deploy:
    provider: script
    script: docker push subhadesigns/node
    on:
        branch: master